@echo off
echo Starting Todo AI Chatbot...

echo Installing dependencies...
pip install -r requirements.txt

echo Starting the application...
uvicorn main:app --host 0.0.0.0 --port 8000 --reload
pause